br:
  operators:
    mundivox:
      prefixes: "*"
      metadata:
        gateways:
          default:
            host: "200.142.96.52"

in:
  operators:
    imimobile:
      prefixes: "*"
      metadata:
        name: "IMImobile"
        gateways:
          default:
            host: "change-me"

kh:
  operators:
    smart:
      metadata:
        gateways:
          default:
            host: "27.109.112.140"
            prefix: false

    mobitel:
      metadata:
        gateways:
          default:
            host: "103.193.204.26"
            prefix: false

    metfone:
      metadata:
        gateways:
          default:
            host: "175.100.93.13"
            prefix: false

sl:
  operators:
    orange:
      metadata:
        gateways:
          default:
            host: "197.215.105.30"
so:
  operators:
    telesom:
      metadata:
        gateways:
          default:
            host: "41.78.73.242"
    golis:
      metadata:
        gateways:
          default:
            host: "41.78.73.242"
    nationlink:
      metadata:
        gateways:
          default:
            host: "41.78.73.242"
    somtel:
      metadata:
        gateways:
          default:
            host: "41.78.73.242"
    hormuud:
      metadata:
        gateways:
          default:
            host: "41.78.73.242"
